In [41]:
import pandas as pd

In [42]:
%run get_team_data.ipynb

In [43]:
%run get_team_data.ipynb

In [ ]:
game_logs

,Name,Date,Age,Tm,Opp,Win/Loss,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,Player Encoding
0,Jakob Poeltl,2016-10-26,21,TOR,Detroit Pistons,W (+18),0,12:47,1,4,...,2,0,0,0,0,5,2,-1.0,-4,9
1,Jakob Poeltl,2016-10-28,21,TOR,Cleveland Cavaliers,L (-3),0,10:49,3,5,...,7,0,0,0,0,1,7,8.0,+9,9
2,Jakob Poeltl,2016-10-31,21,TOR,Denver Nuggets,W (+3),0,17:24,0,3,...,5,0,0,2,0,3,1,0.6,-3,9
3,Jakob Poeltl,2016-11-02,21,TOR,Washington Wizards,W (+10),0,17:23,0,0,...,5,0,1,1,1,6,0,0.2,+8,9
4,Jakob Poeltl,2016-11-04,21,TOR,Miami Heat,W (+9),0,20:04,1,4,...,6,0,1,0,1,2,4,4.2,+6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Bruce Brown,2024-04-07,27,TOR,Washington Wizards,W (+8),0,19:41,4,7,...,2,1,1,0,0,3,9,6.4,-7,0
77,Bruce Brown,2024-04-09,27,TOR,Indiana Pacers,L (-17),0,27:46,7,12,...,3,5,0,0,2,0,16,12.0,-16,0
78,Bruce Brown,2024-04-10,27,TOR,Brooklyn Nets,L (-4),Did Not Dress,Did Not Dress,Did Not Dress,Did Not Dress,...,Did Not Dress,Did Not Dress,Did Not Dress,Did Not Dress,Did Not Dress,Did Not Dress,Did Not Dress,Did Not Dress,Did Not Dress,0
79,Bruce Brown,2024-04-12,27,TOR,Miami Heat,L (-22),0,21:30,5,6,...,4,4,0,0,2,3,14,12.6,-22,0
80,Bruce Brown,2024-04-14,27,TOR,Miami Heat,L (-15),0,20:25,3,5,...,0,0,0,0,1,2,6,1.5,-16,0

In [45]:
advanced_stats

,Rk,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,eFG%,TOV%,ORB%,FT/FGA,eFG%.1,TOV%.1,DRB%,FT/FGA.1,Year,Team Encode
0,1.0,San Antonio Spurs,27.3,57.0,25.0,62,20,7.22,0.29,7.51,...,0.473,14.1,29.5,0.219,0.433,14.8,74.6,0.215,2004,30
1,2.0,Detroit Pistons,27.4,54.0,28.0,59,23,5.84,-0.81,5.04,...,0.461,14.7,30.1,0.247,0.441,15.5,71.8,0.202,2004,9
2,3.0,Indiana Pacers,27.1,61.0,21.0,58,24,5.76,-0.82,4.93,...,0.471,14.1,28.5,0.243,0.459,15.7,73.9,0.218,2004,12
3,4.0,Minnesota Timberwolves,29.7,58.0,24.0,57,25,5.49,0.37,5.86,...,0.486,12.4,26.7,0.207,0.444,12.9,72.5,0.215,2004,18
4,5.0,Sacramento Kings,29.3,55.0,27.0,55,27,5.01,0.40,5.41,...,0.507,13.0,26.0,0.242,0.483,13.7,69.8,0.193,2004,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,26.0,Philadelphia 76ers,28.7,3.0,14.0,4,13,-8.29,1.60,-6.70,...,0.497,12.9,23.6,0.215,0.564,15.8,74.5,0.234,2025,26
26,27.0,Portland Trail Blazers,24.2,7.0,12.0,5,14,-8.42,1.10,-7.32,...,0.488,14.6,29.2,0.193,0.539,14.4,70.4,0.211,2025,28
27,28.0,Utah Jazz,24.7,4.0,14.0,4,14,-9.83,2.09,-7.74,...,0.525,16.0,28.3,0.224,0.561,11.2,73.7,0.196,2025,33
28,29.0,New Orleans Pelicans,25.7,4.0,15.0,3,16,-11.79,0.94,-10.85,...,0.499,13.6,28.2,0.177,0.565,12.5,72.7,0.155,2025,21
29,30.0,Washington Wizards,23.6,2.0,15.0,2,15,-15.29,1.87,-13.42,...,0.506,13.8,20.7,0.184,0.556,11.6,72.6,0.229,2025,34

In [46]:
print(game_logs.columns)

Index(['Name', 'Date', 'Age', 'Tm', 'Opp', 'Win/Loss', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'GmSc', '+/-',
       'Player Encoding'],
      dtype='object')

In [47]:
print(advanced_stats.columns)

Index(['Rk', 'Team', 'Age', 'W', 'L', 'PW', 'PL', 'MOV', 'SOS', 'SRS', 'ORtg',
       'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'eFG%', 'TOV%', 'ORB%',
       'FT/FGA', 'eFG%.1', 'TOV%.1', 'DRB%', 'FT/FGA.1', 'Year',
       'Team Encode'],
      dtype='object')

In [48]:
merged = pd.merge(game_logs, advanced_stats, how='right',left_on=['Year', 'Opp'],right_on=['Year', 'Team'])

KeyError: 'Year'